[package]
name = "omap"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
geo-types = "^0.7.13"
polyline2bezier = {git = "https://github.com/oyhj1801/polyline2bezier"}
proj4rs = { version = "0.1.5", features = ["crs-definitions"] }
strum = "0.27.0"
strum_macros = "0.27.0"
subenum = { version = "1.1.2", default-features = false}
thiserror = "2.0.11"
world_magnetic_model = "0.2.0"
