[package]
name = "omap"
version = "0.1.0"
edition = "2021"
authors = ["Øyvind Hjermstad <@yvind>"]

description = "Open Orienteering Mapper omap file writer"
homepage = "https://github.com/yvind/omap-rs"
repository = "https://github.com/yvind/omap-rs"
readme = "README.md"
license = "MIT"
keywords = ["orienteering", "map", "mapping"]

[dependencies]
geo-types = "0.7.16"
thiserror = "2.0.11"
kiddo = "5.0.3"
linestring2bezier = "0.2.0"
proj4rs = { version = "0.1.5", features = ["crs-definitions"] }
chrono = "0.4.39"
world_magnetic_model = "0.2.0"
